[build]
  # Build command for static site
  command = "npm run build:static"
  
  # Directory to publish (where Vite outputs the built files)
  publish = "dist/public"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
